name: calory_calc
description: Calorie calculator.

version: 1.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.18.0 
  sqflite: any
  path_provider: any
  gradient_widgets: ^0.5.2
  shared_preferences: ^0.5.6+3
  intl: ^0.16.1
  flutter_staggered_grid_view: ^0.3.0
  curved_navigation_bar: ^0.3.2
  font_awesome_flutter: ^8.8.1
  charts_flutter: ^0.9.0
  flutter_launcher_icons: ^0.7.4
  firebase_admob: ^0.9.3+1
  flutter_native_admob: ^2.1.0
  carousel_slider: ^2.1.0
  flutter_config: ^1.0.7
  ff_navigation_bar: ^0.1.4

  auto_size_text: ^2.1.0

  # after 1.0.1

  equatable: ^1.2.5
  flutter_bloc: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
   - assets/bg.png
   - assets/bg2.png
   - assets/selector/slim.svg
   - assets/svg/noMeal.svg
   - assets/svg/dev.svg
   - assets/selector/slimColor.png
   - assets/selector/slim.png

   - assets/selector/normalColor.png
   - assets/selector/normal.png

   - assets/selector/strongColor.png
   - assets/selector/strong.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf

