name: calory_calc
description: Calorie calculator.

version: 1.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Logic and data

  sqflite: any
  path_provider: any
  flutter_config: ^1.0.7
  intl: ^0.16.1
 
  #UI

  flutter_staggered_grid_view: ^0.3.0
  font_awesome_flutter: ^8.8.1
  charts_flutter: ^0.9.0
  carousel_slider: ^2.1.0
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.18.0 

  #Firebase

  firebase_admob: ^0.9.3+1
  flutter_native_admob: ^2.1.0

  # after 1.0.1

  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  auto_size_text: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
   - assets/bg.png
   - assets/bg2.png
   - assets/selector/slim.svg
   - assets/svg/noMeal.svg
   - assets/svg/dev.svg
   - assets/selector/slimColor.png
   - assets/selector/slim.png

   - assets/selector/normalColor.png
   - assets/selector/normal.png

   - assets/selector/strongColor.png
   - assets/selector/strong.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf

